- modules/code-generator/src/cli/run.ts
出码的模版 npm 源应该忘记替换了吧～ 外部只能使用内置 icejs 和 rax 模版了。另外这里扩展模版是不是应该不局限使用 @alilc/ 的 namespace？
> fix: 出码模版 npm 源

- modules/code-generator/CHANGELOG.md
- modules/code-generator/package.json
- modules/code-generator/src/plugins/common/esmodule.ts
- modules/code-generator/test-cases/react-app/demo3/expected/demo-project/src/pages/Test/index.jsx
- modules/code-generator/tests/bugfix/icejs-import-wrong-naming.schema.json
- modules/code-generator/tests/bugfix/icejs-import-wrong-naming.test.ts
解决问题：对于 componentsMap 中如下这种 componentName 和 exportName 不一致的场景，期望生成的是 `import Foo from "example-package"` ，然而之前实际生成的却是   `import Bar from "example-package"` ，现已修正：
```json
{
"package": "example-package",
"version": "1.2.3",
"exportName": "Bar",
"componentName": "Foo",
"destructuring": false
}
```
详见 icejs-import-wrong-naming.schema.json 和 icejs-import-wrong-naming.test.ts
> hotfix: 出码模块 - 解决 componentName 和 exportName 不一致时生成的 import 语句的问题

- packages/designer/src/designer/drag-ghost/index.tsx
- packages/designer/src/designer/setting/setting-prop-entry.ts
- packages/designer/src/document/node/props/props.ts
- packages/designer/src/document/node/props/value-to-source.ts
- packages/editor-core/src/widgets/tip/utils.ts
- packages/rax-simulator-renderer/src/rax-use-router.js
- packages/rax-simulator-renderer/src/renderer.ts
- packages/react-simulator-renderer/src/renderer.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- packages/rax-simulator-renderer/src/renderer.ts
- packages/react-simulator-renderer/src/renderer.ts
fix https://github.com/alibaba/lowcode-engine/issues/124
查找选中节点，在 React 17 的判断条件为以 `__reactFiber$` 开头
> fix: 修复React17选中组件bug

- packages/designer/src/designer/setting/utils.ts
- packages/editor-core/src/di/setter.ts
- packages/types/src/setter-config.ts
修复开发 setter 使用 hooks 的错误。
使用一个 `isDynamic` 属性来进行标识是否为动态 setter，为了向下兼容，这个值默认为 true，所以 FC 需要显式设置为 false。
可以通过以下两种方式去设置 `isDynamic`：
1. 物料描述的 setter 配置项设置 `isDynamic` 为 false
2. 注册 setter 时设置 `isDynamic` 为 false，如下图所示：
> fix: fix setter hooks error

- packages/editor-core/src/config.ts
严格模式存在过滤，将数据源引擎请求处理器映射加到了 VALID_ENGINE_OPTIONS 中
```js
const isValidKey = (key: string) => {
const result = (VALID_ENGINE_OPTIONS as any)[key];
return !(result === undefined || result === null);
};
```
> fix: 🐛 修复数据源引擎请求处理器映射严格模式下被过滤的问题

- packages/shell/src/setting-prop-entry.ts
lowcode-engine-ext 的 object-setter 会调用 [field.createField](https://github.com/alibaba/lowcode-engine-ext/blob/b4a9d008c3/src/setter/object-setter/index.tsx#L215) 来创建 field，然后调用 [createSettingFieldView](https://github.com/alibaba/lowcode-engine-ext/blob/b4a9d008c3/src/setter/object-setter/index.tsx#L228) 来创建 settingFieldView。createSettingFieldView 会读取 [item.isGroup](https://github.com/alibaba/lowcode-engine/blob/44ad744aac/packages/editor-skeleton/src/components/settings/settings-pane.tsx#L278) 来判断是否使用 SettingGroupView。SettingGroupView 又会使用 [field.items](https://github.com/alibaba/lowcode-engine/blob/44ad744aac/packages/editor-skeleton/src/components/settings/settings-pane.tsx#L271) 遍历创建 fieldView
所以 shell 的 SettingPropEntry 要提供访问 isGroup 和 items 这两个变量，否则通过 field.createField …
> feat: add isGroup & items to shell SettingPropEntry

- packages/editor-skeleton/src/transducers/addon-combine.ts
如果按照原来讨论的，直接在 metadata.configure 上挂的话，经过测试，还是不能影响整个的 metadata。猜测是进到这个函数里的 metadata 已经是被复制过了，所以又改回了之前的方案，这个方案经过测试可以使用。
> fix: addon-combine affect metadata unexpectedly

- packages/editor-skeleton/src/components/popup/index.tsx
背景：希望在点击 popup 面板之外的地方，能够自动关闭 popup
ConfigProvider 是为了让 next 的弹窗弹到 popup 里面，不然 popup 再弹窗会默认追加到 body 上，点击这些二次创建的弹窗就会关闭 popup
engine-variable-setter-dialog 是为了定制 vs-variable-setter 的 container（感觉有点耦合，可以讨论下怎么做合理）
> feat: refine pop drawer

- packages/designer/src/builtin-simulator/host.ts
- packages/editor-core/src/config.ts
So that the `customizeIgnoreSelectors` can dynamically decide whether the target of the event can respond to the event.
> feat: pass e to customizeIgnoreSelectors

- packages/designer/src/designer/designer.ts
- packages/editor-core/src/editor.ts
- packages/types/src/editor.ts
在部分物料组件异步追加物料时，若触发 assetLoader ，代码执行时序错乱
> fix: designer/loadIncrementalAssets await Sequential

- packages/utils/src/asset.ts
@alilc/lowcode-utils/es/aeeset.js中 export {AssetItem, AssetType, AssetLevels, Asset, AssetList, AssetBundle, AssetLevel, AssetsJson} from '@alilc/lowcode-types' 向外导出不存在的变量（@alilc/lowcode-types下没有这样的变量），vite使用的esbuild，esbuild的transform环节，会报错，具体文件地址和报错信息如下图。webpack可能会对这种有处理，不会报错。
> fix: delete unused typescript types

- packages/editor-skeleton/src/components/popup/index.tsx
When there are nesting Drawers, click on one Drawer will close the underlying Drawer.
Pass a div as popupContainer to nesting Drawer will fix this behavior.
> feat: refine nesting drawer

- modules/code-generator/src/utils/compositeType.ts
- modules/code-generator/tests/utils/compositeType.test.ts
生成 dataSource 时候，如果 variable 为空字符串，在字符串拼接的时候啥都没了，而作为代码应该拼接为两个引号
test case 有注释说明
暂时 test case 都跑过了，但需要维护者全面评估下这个改动，或者看有没其他合理方案来修复
> fix: fix empty string lost when  generate variable

- packages/designer/src/designer/detecting.ts
- packages/designer/src/designer/index.ts
- packages/engine/src/modules/designer-cabin.ts
- packages/engine/src/modules/symbols.ts
- packages/engine/src/modules/utils.ts
- packages/plugin-outline-pane/src/views/tree.tsx
- packages/shell/src/detecting.ts
- packages/shell/src/document-model.ts
- packages/shell/src/node.ts
- packages/shell/src/project.ts
- packages/shell/src/prop.ts
- packages/shell/src/selection.ts
- packages/shell/src/symbols.ts
- packages/types/src/editor.ts
feat: add APIs for plugin-outline-pane which will be splitted in near future
- Detecting.current 当前 hover 的节点
- Node.isLocked 获取当前节点的锁定状态
- DocumentModel.checkNesting 检查拖拽放置的目标节点是否可以放置该拖拽对象
- Node.lock 设置节点锁定状态
- Node.getExtraProp 新增 createIfNone 参数
- Prop.remove 移除 prop 值
- Selection.getTopNodes 获取选区的顶层节点
- project.onRemoveDocument 绑定删除文档事件
> feat: add APIs for plugin-outline-pane which will be splitted in near future

- packages/designer/src/plugin/plugin-types.ts
- packages/engine/src/modules/designer-types.ts
Now you can get ctx / options / pluginName / meta with type assistant~
> refactor: provide a typing for PluginConfigCreator

- packages/shell/src/document-model.ts
- packages/shell/src/history.ts
fix: fixed history[historySymbol] appearing undefined under partial execution order
修复在部分执行顺序下，history[historySymbol] 出现 undefined
如图：
原因：
部分情况下 InnerDocumentModel history 方法还未初始化成功，这时候 document.getHistory() 的值为 undefined。
这时候 shell/history 下的方法调用都会出现错误
> fix: fix historySymbol is undefined causing errores when calling the history method

- packages/designer/src/builtin-simulator/host.ts
- packages/designer/src/builtin-simulator/renderer.ts
- packages/designer/src/document/history.ts
- packages/engine/src/modules/utils.ts
- packages/react-simulator-renderer/src/renderer.ts
- packages/renderer-core/src/hoc/leaf.tsx
- packages/renderer-core/src/renderer/base.tsx
- packages/renderer-core/tests/hoc/leaf.test.tsx
- packages/renderer-core/tests/renderer/__snapshots__/renderer.test.tsx.snap
- packages/types/src/index.ts
- packages/types/src/start-transaction.ts
- packages/utils/package.json
- packages/utils/src/index.ts
- packages/utils/src/start-transaction.ts
feat: add common.utils.startTransaction API to change multi nodes
背景：在一些用户操作的场景下，需要批量操作页面上的多个节点的 Props，这时候需要给用户提供一个批操作但是只渲染一次的方法。
使用示例
```
AliLowCodeEngine.common.utils.executeTransaction(() => {
node1.setProps();
node2.setProps();
node3.setProps();
// ...
}, 'repaint');
```
类似于 mobx @action.bound 中的函数执行只触发一次渲染
> feat: add common.utils.executeTransaction API to change multi nodes

- specs/lowcode-spec.md
- specs/material-spec.md
修改点：
1. 移除物料描述协议中最后一段对搭建协议的描述，此部分直接有搭建协议详细描述比较好；
2. 搭建协议中新增全局的 config / meta / dataSource / css / constants 等 5 个字段，重新给协议顶层的 10 个字段排序；
3. 将表格中的 `string|function` 优化成 github styling markdown，优化后：`string\|function` 等；
4. 删除搭建协议 3.1 段落，跟 2 内容重复了；
> feat: add 5 global top-most attributes of lowcode-spec

- packages/designer/src/designer/dragon.ts
修复 RGL 容器的卡顿问题。
复现场景，当拖拽一个组件到  RGL 容器中之后，再触发点击，即 mouseup 事件会触发 rgl.drop，此时实际上没有进行拖拽动作。此时的父子组件的关系是有问题的，触发的 rgl.drop 导致 RGL 场景奔溃。
新增 _dragging （dragstart 时才会设置为 true）判断，再进行 rgl.drop 事件的触发。
> fix: fix rgl container crash problem, remove invalid rgl.drop event

- packages/editor-skeleton/src/components/settings/settings-pane.tsx
- packages/types/src/field-config.ts
fixed: https://github.com/alibaba/lowcode-engine/issues/1255
问题相关 PR：https://github.com/alibaba/lowcode-engine/commit/fcfce3cbeb5a53600c40aea07ffef19c9c9591c4
问题原因：
antd 的物料配置如下：
其中 Antd 的 rowSelection 值类型默认为 bool，但是当其打开时，其值是一个 object。
在 1.0.15 之前的版本，也就是这个 PR 之前，原来 rowSelection.type 不会进行初始化，在**本次变更**之后，rowSelection.type 进行了初始化配置。 rowSelection.type 会执行 value = field.getValue(); 这一步会重新将 rowSelection 置为 type:map 类型的空对象。在下一次获取 rowSelection 的值时，由于 items 都没有初始化，返回的还是 undefined，导致重复循环该步骤。
本次 PR 修复问题并将 SettingFieldView 相关的代码进行重构：
1.将 setter 相关的信息初始化和默认值初始化放到 constructor
2.只有包含 initialValue 的才会计算 value。
> fix: fix the problem of crash caused by infinite loop in antd scene

- docs/docs/api/plugins.md
- docs/docs/participate/flow.md
- packages/designer/jest.config.js
- packages/designer/src/plugin/plugin-context.ts
- packages/designer/src/plugin/plugin-manager.ts
- packages/designer/src/plugin/plugin-types.ts
- packages/designer/tests/plugin/plugin-manager.test.ts
- packages/engine/src/engine-core.ts
将plugin context的api灌装逻辑移到了engine-core, 并补充了common api，为下一步彻底接触 designer 和 shell 循环依赖做准备
> feat: remove circular dependency between designer and shell

- .github/CODEOWNERS
- packages/designer/src/builtin-simulator/utils/parse-metadata.ts
- packages/designer/tests/builtin-simulator/utils/parse-metadata.test.ts
为LowcodeTypes.shape函数增加默认值，防止空值时的运行时错误。
这个问题出现在低代码引擎集成到@umijs/max项目并且版本号大于等4.0.30时，此版本引入react-helmet-async，这个包中有如下图1用法，最终导致在运行期间报错。报错如下图2。
报错如下
> fix: add null protection for LowcodeTypes.shape

- docs/docs/specs/lowcode-spec.md
两点修改：
1. 支持 JSSlot 节点的 value 为一个 NodeSchema 对象，现协议仅支持 NodeSchema[]；
2. 将 Array<Type> 形式改写成 Type[]，这是 TypeScript 推荐的方式；
> feat(spec): support type NodeSchema when the Node is JSSlot

- packages/designer/src/document/node/props/prop.ts
- packages/types/src/schema.ts
部分场景存在
```js
var slotSchema = {
componentName: 'Slot',
...
props: {
slotName / slotTitle / slotParams 
}
}
```
的数据结构，而引擎对于这类结构会丢失 props 下的 3 个属性，这个 PR 将数据补全~
> fix: compatible with SlotSchema which doesn't have title / name / params

- packages/editor-skeleton/src/transducers/addon-combine.ts
为事件设置器绑定的函数模板增加return，解决物料内部需要根据使用侧绑定的函数来控制内部状态的需求，例如弹窗中确认按钮根据onOk函数是否结束并返回bool值控制按钮的loading以及是否关闭弹窗（类似ModalForm）
> feat: add function return for event setter

- packages/utils/src/check-types/is-isfunction.ts
fix: fix isJSFunction lacks the judgment of the old version of the protocol
关联 PR：https://github.com/alibaba/lowcode-engine/pull/1270/files
> fix: fix isJSFunction lacks the judgment of the old version of the protocol

- packages/plugin-outline-pane/src/locale/en-US.json
- packages/plugin-outline-pane/src/locale/zh-CN.json
- packages/plugin-outline-pane/src/views/filter-tree.ts
- packages/plugin-outline-pane/src/views/filter.tsx
- packages/plugin-outline-pane/src/views/pane.tsx
- packages/plugin-outline-pane/src/views/tree-node.tsx
修复当前 `develop` 分支大纲树存在的文字显示问题，以及完善国际化的文本显示。
> fix(plugin-outline-pane): fix text display and improve i18n

- packages/engine/src/engine-core.ts
fix: fix the problem caused by the default metadataTransducer registration timing being too late
> fix: fix the problem caused by the default metadataTransducer registration timing being too late

- packages/designer/src/builtin-simulator/renderer.ts
- packages/designer/src/document/document-model.ts
- packages/designer/src/document/node/node.ts
- packages/renderer-core/src/hoc/leaf.tsx
- packages/renderer-core/src/renderer/base.tsx
- packages/renderer-core/src/renderer/renderer.tsx
- packages/renderer-core/src/types/index.ts
- packages/renderer-core/tests/hoc/leaf.test.tsx
- packages/renderer-core/tests/renderer/base.test.tsx
- packages/renderer-core/tests/utils/node.ts
feat: the renderer-core leaf component removes the react.createElement call
fixed https://github.com/alibaba/lowcode-engine/issues/835
fixed https://github.com/alibaba/lowcode-engine/issues/575
> feat: the renderer-core leaf component removes the react.createElement call

- packages/designer/src/document/node/props/prop.ts
当判断 data.value 是一个 { componentName: 'Slot' } 时，应该将 data.value.children 传给下方的 children~
当前传递的是整个 data.value，将导致 Slot 多层嵌套
> fix: getting slot children incorrectly

- CONTRIBUTOR.md
- packages/designer/src/builtin-simulator/bem-tools/border-resizing.tsx
VC组件通过prototype中的canResizing函数来配置组件某一边是否可拖拽,并在componentDidMount绑定resize事件,但由于单边的div元素采用了动态渲染,当canResizing发生变化时div会销毁然后重新挂载,但是挂载后并没有重新绑定拖拽事件,导致无法重新拖拽
两种修复方法:  
- 将动态渲染修改为通过style控制显示隐藏即可
- 或者componentDidUpdate里重新绑定一次,但组件每次更新都会重新绑定,对于拖拽调整组件宽度长度等场景会频发触发解绑和绑定
目前的commit是通过第一种方式修复的
```jsx
componentDidMount() {
this.willBind();
}
render() {
if (!observed.hasOffset) {
return null; //   ⬅️动态渲染
}
return (
<div>
{/* ⬇️ 动态渲染 ⬇️ */}
{triggerVisible.includes("N") && (
<div
ref={(ref) => {
this.outlineN = ref;
}}
className={classNames(baseSideClass, "n")}
style={{
height: 20,
transform: `translate(${offsetLeft}px, ${offsetTop - 10}px)`,
width: offsetWidth,
}}
/>
)}
</div>
);
}
```
> fix(designer): 修复VC组件canResizing发生变化时无法拖拽

- packages/plugin-outline-pane/src/controllers/tree-node.ts
- packages/plugin-outline-pane/src/views/tree-branches.tsx
- packages/plugin-outline-pane/src/views/tree-node.tsx
- packages/plugin-outline-pane/src/views/tree-title.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/1672
这里的 treeNode 会在多个组件中使用，这里的事件会被覆盖，所以用 event emit 来处理更合适一些。
> fix: fix the problem that the outline pane tree cannot be expanded

- docs/docs/api/event.md
- packages/types/src/shell/api/event.ts
> docs: 事件api文档中emit使用了off的接口

- docs/docs/specs/material-spec.md
- packages/editor-skeleton/src/components/settings/settings-pane.tsx
- packages/types/src/shell/type/field-extra-props.ts
新增 ignoreDefaultValue 属性描述
用于满足复合属性的配置场景：
如下图的 AntD Table 物料描述，当 pagination 为 {} 则展示翻页，当 pagination 为 false 时则不展示翻页。而原来的物料描述中只有 condition 字段，这个字段只是控制显示隐藏与否，和设置 defaultValue 没有关系，因此需要新增 ignoreDefaultValue 来配置是否忽略 defaultValue 的字段。
> feat: material spec add ignoreDefaultValue field to component property description

- packages/designer/src/builtin-simulator/host.ts
- packages/react-simulator-renderer/src/renderer.ts
fix the missing i18n param in simulator and renderer so that display i18n of "Drag and drop components or templates here" in  simulator: https://github.com/alibaba/lowcode-engine/pull/1497/files
> fix: missing i18n param in simulator and renderer

- packages/designer/src/designer/detecting.ts
- packages/designer/src/designer/location.ts
- packages/designer/src/designer/setting/setting-field.ts
- packages/designer/src/designer/setting/setting-prop-entry.ts
- packages/designer/src/designer/setting/setting-top-entry.ts
- packages/designer/src/document/document-model.ts
- packages/designer/src/document/node/exclusive-group.ts
- packages/designer/src/document/node/node.ts
- packages/designer/src/document/node/props/prop.ts
- packages/designer/src/document/node/props/props.ts
- packages/designer/src/project/project.ts
- packages/shell/src/model/condition-group.ts
- packages/shell/src/model/history.ts
- packages/workspace/src/index.ts
- packages/workspace/src/workspace.ts
在 TypeScript 中，使用 export interface 导出的接口，在引入时确实需要使用 import type 来声明。
这是因为 import type 声明的是类型，而不是值，这样可以避免在编译时将接口的定义包含在输出文件中，从而减小输出文件的大小。另外，使用 import type 还可以避免出现循环依赖的问题。
> fix: ts interface error

- docs/docs/api/project.md
- packages/designer/src/project/project.ts
- packages/shell/src/api/project.ts
- packages/types/src/shell/api/project.ts
- packages/types/src/shell/type/app-config.ts
- packages/types/src/shell/type/project-schema.ts
添加设置项目配置的方法，可以通过 `project.setConfig('key', value)` 来这只 projectSchema 的 config 属性值
> feat: add setConfig method for project

- packages/react-simulator-renderer/src/renderer.ts
duplicate key "locale" in renderer.ts
> fix: duplicate key "locale" in renderer.ts

- packages/types/src/shell/type/metadata.ts
- packages/types/src/shell/type/node-data.ts
优化类型
1. 经过测试，IPublicTypeNodeData 是支持渲染  IPublicTypeI18nData
2. 将 ConfigureSupportEvent 配置作为接口而非类型别名，以便更好的扩展该类型。在一些场合(setter) 可能个需要对事件配置做扩展配置
```ts
declare module '@alilc/lowcode-types' {
export interface ConfigureSupportEventConfig {
template?: string;
}
}
export {}
```
> feat: optimized lowcode types

- packages/plugin-outline-pane/src/views/tree-node.tsx
> fix: fix that the outline tree does not respond to modal addition/deletion related operations

- .github/workflows/cov packages.yml
- .github/workflows/test packages.yml
- packages/renderer-core/jest.config.js
- packages/renderer-core/tests/utils/common.test.ts
- packages/utils/jest.config.js
- packages/utils/src/is-react.ts
- packages/utils/test/src/build-components/buildComponents.test.ts
- packages/utils/test/src/is-react.test.ts
fixed https://github.com/alibaba/lowcode-engine/issues/1884
fixed https://github.com/alibaba/lowcode-engine/issues/1850
> fix(utils): isReactComponent not including react.memo

- packages/designer/src/document/node/props/prop.ts
- packages/designer/tests/document/node/props/prop.test.ts
该 PR，为了解决 loopArgs不返回[undefined, undefined]，但是会导致需要设置 prop value 为 undefined[] 类型的设置器，无法获取正确的值。
https://github.com/alibaba/lowcode-engine/pull/141/files
Closes https://github.com/alibaba/lowcode-engine/issues/1891
> fix(prop): fix prop.export can not correctly export undefined[]

- .github/workflows/check base branch.yml
- .github/workflows/help wanted.yml
- .github/workflows/insufficient information.yml
- .github/workflows/test modules.yml
- .github/workflows/test packages.yml
Feature:
Check base branch whether it's going to merge into develop branhch, otherwise make a comment to let PR user take a look at [Contribution Guideline](https://lowcode-engine.cn/site/docs/participate/flow).
> feat: add workflow for checking base branch

- packages/shell/src/api/plugins.ts
plugins.delete 取得是name值进行删除，
但是实际上LowCodePluginRuntime的实例被挂载到了Symbol(plugin-instance)，导致plugin. name不能被直接获取
我无法对lowcode-engine进行开发调试，属于盲改，酌情合并。
> fix: fix proxy plugins.delete not added async

- packages/designer/src/plugin/plugin-manager.ts
更安全的plugins.delete，降低使用者心智负担
```js
// e.g. 1
plugins.getAll().forEach((plugin) => {  // 期望全部删除，实际每次仅删除一半
plugins.delete(plugin.pluginName)
})
// e.g. 2
plugins.delete('OutlinePlugin')  // 正常删除
plugins.delete('___component_meta_parser___') // 无法删除，因 index 是删除 OutlinePlugin 插件前的保存的位置，实际会删除其它plugin
```
e.g.2 也可以通过 #1962 解决
```js
await plugins.delete('OutlinePlugin')
await plugins.delete('___component_meta_parser___')
```
> chore: safer plugins.delete

- packages/plugin-outline-pane/src/views/pane.tsx
currentTree 仅在 onSimulatorRendererReady 生命周期 赋值一次，后续若改变document，大纲图节点未更新
> fix: fix outlinePane treeView render only once

- modules/code-generator/src/parser/SchemaParser.ts
> fix: skip internal dep when type is pages, closes #2049

- modules/code-generator/src/plugins/common/styleImport.ts
> fix: add Fusion-UI style for code generation

- packages/shell/src/api/setters.ts
fix https://github.com/alibaba/lowcode-engine/issues/2059
> fix(setters): getSettersMap function this bind error

- packages/designer/src/document/document-model.ts
The component which has no npm info should be regarded as a `lowCode` comp,
otherwise, it will be absent in componentsMap which dues to incomplete asynchronous loading of components needed.
And also can not tell which kind of component is in Code Generation Phase.
> fix: comp which has no npm info should be regarded as lowCode comp

- packages/editor-skeleton/src/components/settings/settings-pane.tsx
- packages/utils/src/misc.ts
- packages/utils/test/src/misc.test.ts
Refs: #177 #500 #1938 #1930 
Summary: **supportVariable in single prop definition should OVERLAP the global valve, a.k.a. supportVariableGlobally**~
For Example:
1. supportVariable: false + supportVariableGlobally: true 
-> false
2. supportVariable: true | undefined + supportVariableGlobally: true 
-> true
3. supportVariable: true | undefined + supportVariableGlobally: false 
-> true
> fix: supportVariable SHOULD take precedence over supportVariableGlobally

- modules/code-generator/src/postprocessor/prettier/index.ts
在types/core.ts文件的FileType枚举中支持ts和tsx文件但是出码的时候没有格式化这两种文件，因此增加这两种文件的格式化
> feat(ts file format): 出码生成的*.ts和*.tsx文件使用babel格式化

- packages/designer/src/builtin-simulator/renderer.ts
- packages/types/src/shell/type/index.ts
- packages/types/src/shell/type/simulator-renderer.ts
将 simulator 类型声明从 designer 中提取到 types 中，便于其他框架的 simulator 实现
> feat: extract simulator type

- packages/types/src/shell/type/metadata.ts
The [document] says we can pass `template` value in `configure.supports.events`.
The implementation shows that both `function-setter` and `event-setter` emit `eventBindDialog.openDialog` event, and `EventBindDialog` truly supports using `template` value, [ref].
So fix the metadata type to allow `template` field.
[document]: https://lowcode-engine.cn/site/docs/guide/appendix/setterDetails/event#%E4%BA%8B%E4%BB%B6%E6%96%B0%E5%BB%BA%E5%87%BD%E6%95%B0%E6%A8%A1%E6%9D%BF
[ref]: https://github.com/alibaba/lowcode-engine-ext/blob/main/src/plugin/plugin-event-bind-dialog/index.tsx#L283
> fix(lowcode-types): allow `template` field in configure.supports.events

- docs/docs/api/project.md
project API下的变量`currentDocument`和方法`getCurrentDocument` 都是获取当前的document，重复了。
> doc(projectapi): 删除重复的getCurrentDocument方法

- modules/code-generator/src/postprocessor/prettier/index.ts
原有的 babel parser 对于一些新的 ts 语法兼容性不好，会导致如果一些 ts 的代码解析时报错，如
```
class A {
[key: string]: any; // 这里解析不了
}
```
升级到 babel-ts 后可以修复此问题，两者的区别见 prettier 文档
https://prettier.io/docs/en/options.html#parser
> fix(code-generator): upgrade prettier parser from babel to babel-ts, fix some ts parse error

- docs/docs/guide/expand/editor/metaSpec.md
- packages/types/src/shell/type/field-extra-props.ts
移除 IPublicTypeFieldExtraProps.virtual 相关定义。
> IPublicTypeFieldExtraProps.virtual 只有 ts 定义，没有相关逻辑，也不属于物料协议，属于多余的代码。
fixed https://github.com/alibaba/lowcode-engine/issues/2281
> feat: remove IPublicTypeFieldExtraProps.virtual definition

- docs/docs/faq/faq009.md
完善“物料出现 Component Not Found 相关报错” FAQ
> docs: update faq009.md

- packages/editor-core/src/editor.ts
Reverts alibaba/lowcode-engine#2388
当资产包 URL 加载出现问题时，资产包有缺失，正常渲染的情况下，会造成这部分组件的 schema 异常，例如 componentMap 异常，不应该做 catch 处理。
> revert "fix(material): fix rendering is blocked, when the url in the asset fails to load"

- packages/renderer-core/src/renderer/base.tsx
- condition 为 false 不执行解析 children props
- 循环组件循环数据为空数组时不继续执行 `__createVirtualDom`
> fix: do not parse props when condition is false or loop data is empty

- packages/designer/package.json
在monorepo 的 root 中已经将 @alilc/build-plugin-lce 作为 devDeps 了，这里直接删掉就可以了
> fix: remove unnecessary dep

- packages/editor-skeleton/src/components/settings/settings-primary-pane.tsx
没发现这个 `class` 有什么意义，只会平白对一个 warning
> fix: remove `class` prop

- package.json
这是什么问题
`react-error-overlay` 6.0.11 版本里面会有 `process.platform` 在浏览器中会报错， webpack v5 才支持这种方式
详情 → https://github.com/facebook/create-react-app/issues/11773
> 固定 react-error-overlay 的版本

- packages/renderer-core/src/renderer/base.tsx
修复当children值为数值0的时候无法正确渲染出来的问题。
> fix: fix rendering failure when children is number 0

- packages/react-simulator-renderer/test/src/renderer/__snapshots__/demo.test.tsx.snap
- packages/renderer-core/src/hoc/index.tsx
- packages/renderer-core/src/renderer/base.tsx
- packages/renderer-core/src/renderer/renderer.tsx
- packages/renderer-core/src/types/index.ts
- packages/utils/src/is-react.ts
普通函数组件报错（比如需要绑定一个数组绑定成了数字）修改配置后可以恢复
forwardRef 组件报错，比如需要绑定一个数组绑定成了数字）修改配置后无法恢复（修要手动执行 simulatorHost.rerender()才能恢复）
1. 如果物料组件不能接受 ref，就包裹一个类组件
https://github.com/alibaba/lowcode-engine/blob/bf980c98ea62eb969af29cfc810f497c3f772509/packages/utils/src/build-components.ts#L114-L118
2. 原有的 patchDidCatch 逻辑只对类组件生效，这会导致 forwardRef 的组件无法捕获错误
针对 forwardRef 进行特殊处理
> fix: 修复 forwardRef 组件的错误无法捕获

- packages/renderer-core/src/hoc/index.tsx
- packages/renderer-core/src/renderer/base.tsx
-  **hoc 组件缓存**
防止每次 setState 都全量mount
> fix: hoc 组件缓存问题

- packages/types/src/shell/type/remote-component-description.ts
- packages/utils/src/asset.ts
- packages/utils/src/script.ts
`AssetJson` 支持的 `components` 支持 `esmodule` 的脚本。例如:
```json5
{
"version": "0.0.1",
"packages": [
// ...
],
"components": [
{
"url": {
"type": "jsUrl",
"content": "http://localhost:3000/meta.js",
"scriptType": "module"
},
"exportName": "MyCompoentMeta",
"package": {
"npm": "my-component"
}
}
]
}
```
> feat(utils|types): add esmodule support for component meta resources

- packages/designer/src/builtin-simulator/bem-tools/border-selecting.tsx
addBuiltinComponentAction中icon的dom无法获取node节点，建议在 createAction中的 createIcon 补充 key，node参数
issuesId：#2622
[](https://github.com/alibaba/lowcode-engine/issues/2622)
> fix: createIcon props

- docs/docs/participate/prepare.md
- packages/renderer-core/src/renderer/base.tsx
> fix: fixed string trim issue

- packages/renderer-core/src/renderer/base.tsx
- packages/renderer-core/src/renderer/component.tsx
> fix: recover component lifecycle and avoid execute from scope __proto__

- packages/designer/src/document/node/node.ts
- packages/designer/tests/document/node/node.test.ts
> fix: Improve code and simplify logic

- packages/renderer-core/src/renderer/base.tsx
remove renderer lifeCycle method compatibility with uipaas
> fix(renderer-core): remove renderer lifeCycle method compatibility with uipaas

- packages/renderer-core/src/renderer/base.tsx
fix：https://github.com/alibaba/lowcode-engine/issues/2704
在getDerivedStateFromProps()加了一个undefined校验，没有直接改executeLifeCycleMethod()，以免影响其他方法。
> fix: executeLifeCycleMethod return bug in renderer

- packages/renderer-core/src/renderer/base.tsx
fix: scope props merge defaultProps
> fix: scope props merge defaultProps

- packages/plugin-outline-pane/src/views/filter-tree.ts
- packages/plugin-outline-pane/src/views/tree-node.tsx
- packages/plugin-outline-pane/src/views/tree-title.tsx
1. 在搜索的时候，没有命中搜索结果的节点也会显示出来，但点击后就会消失；
2. 命中搜索结果的节点虽然展示出来的，但其父节点 Title 前的 icon 还是收起的 icon；
3. 取消搜索后没有展示全部的节点，但点击后就展示出来，有时点击也不会展示出来，只能刷新页面；
4. 再次搜索后，命中搜索结果的节点没有变红突出。
复现录屏：
https://github.com/alibaba/lowcode-engine/assets/68992947/94e0d620-1353-4660-9d47-205b9592de73
搜索时会修改 TreeNode 内的某些属性，但由于 TreeNode 对象比较复杂，没有触发大纲树中组件的重新渲染。
搜索时会额外出发 forceRender 参数的变更，大纲树中组件监听该参数的变更。
> fix: trigger onFilterResultChanged when filtered

- .github/workflows/publish docs.yml
- .github/workflows/publish engine beta.yml
- .github/workflows/publish engine.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- packages/designer/src/document/node/node.ts
close https://github.com/alibaba/lowcode-engine/issues/2677
> fix(designer): node.ts cannot generate declaration file

- packages/editor-core/src/di/setter.ts
- packages/editor-skeleton/src/components/settings/settings-pane.tsx
- packages/editor-skeleton/src/transducers/parse-props.ts
- packages/types/src/shell/type/field-extra-props.ts
- packages/types/src/shell/type/registered-setter.ts
fixed https://github.com/alibaba/lowcode-engine/issues/2887
> feat(setter): add field ts

- packages/react-simulator-renderer/src/renderer.ts
detached node has children will return false, causing memory leaks.
> fix(react-simulator-renderer): detached node has children

- packages/renderer-core/src/utils/common.ts
Reverts alibaba/lowcode-engine#2271
> Revert "fix: keep `this` in parse expression function"
