modules/material-parser/package.json, modules/material-parser/src/parse/transform.ts, modules/material-parser/src/utils.ts
1. rt;
2. check module before install it;
=> fix no defaultValue in ts parser

packages/engine/README-zh_CN.md, packages/engine/README.md
预览效果： https://github.com/lecepin/lowcode-engine/blob/develop/packages/engine/README.md
---
相关文章：[解决写文档对于图片边框的强迫症](https://juejin.cn/post/7073011930859831303)
使用工具：[https://github.com/lecepin/image-border](https://github.com/lecepin/image-border)
=> style: Optimize the image style of the README document

packages/renderer-core/src/utils/data-helper.ts
=> refactor: 去除数据源历史兼容逻辑

packages/plugin-designer/package.json
https://github.com/alibaba/lowcode-engine/pull/267
=> fix: add  lowcode-designer, lowcode-utils dependencies

packages/shell/src/node.ts
fix https://github.com/alibaba/lowcode-engine/issues/311
=> feat: add mergeChldren API for shell node

packages/designer/src/project/project.ts
fix: fix internal project.getSchema default stage is error
=> fix: fix internal project.getSchema default stage is error

packages/designer/src/builtin-simulator/bem-tools/border-resizing.tsx, packages/designer/src/utils/misc.ts
fix https://github.com/alibaba/lowcode-engine/issues/364
=> fix: use uppercase resize trigger names based on material spec

packages/editor-core/package.json, packages/editor-core/src/config.ts
=> feat: 🎸 设计态支持数据源引擎配置

packages/renderer-core/src/utils/common.ts
fix: https://github.com/alibaba/lowcode-engine/issues/509
=> feat: modify the output method of rendering module parsing errors

packages/designer/src/builtin-simulator/host.ts, packages/editor-core/src/config.ts, packages/react-simulator-renderer/src/renderer.ts
react-renderer 跟 react-simulator-renderer 的 utils 跟  constants 不一致会导致搭建页面直接报错
相关 issues: 
https://github.com/alibaba/lowcode-engine/issues/461
https://github.com/alibaba/lowcode-engine/issues/419
https://github.com/alibaba/lowcode-engine/issues/393
=> feat: sync utils/constants

CONTRIBUTOR.md, packages/editor-core/src/config.ts
fix: missing engine options config  [deviceClassName]  info
=> fix: missing engine options config info

package.json, scripts/setup.js, scripts/start.js
在 Win10 上执行 npm run setup 测试过了，可行无报错。
=> chore: npm run setup 和 npm run start 命令适配 win 系统

packages/shell/src/document-model.ts
=> feat: add onMountNode event for DocumentModel

packages/utils/src/asset.ts
Reverts alibaba/lowcode-engine#897
=> Revert "fix: delete unused typescript types"

packages/react-simulator-renderer/src/renderer-view.tsx, packages/renderer-core/src/renderer/page.tsx
fix: https://github.com/alibaba/lowcode-engine/issues/722
=> fix: fix render module state expression initialization exception

packages/utils/src/asset.ts, packages/utils/src/is-css-url.ts
fixed https://github.com/alibaba/lowcode-engine/issues/901
=> fix: fix css resources with parameters not loading correctly

packages/renderer-core/package.json, packages/renderer-core/src/utils/common.ts, packages/utils/src/asset.ts
=> fix: change typescript type export to export type

specs/assets-spec.md, specs/lowcode-spec.md, specs/material-spec.md
=> feat: added lowcode engine standard specs

packages/renderer-core/src/renderer/base.tsx
fixes https://github.com/alibaba/lowcode-engine/issues/943
=> fix: fixed an issue where materials would be rendered multiple times

packages/plugin-outline-pane/src/views/filter.tsx
fix unique key prop warning for filter component
=> fix(filter):  unique key prop warning

packages/renderer-core/package.json, packages/renderer-core/src/utils/common.ts
Close https://github.com/alibaba/lowcode-engine/issues/984
=> chore: remove moment.js

packages/shell/src/document-model.ts
=> refactor: modify parameter types of onMountNode

specs/material-spec.md
物料协议规范 - 2.2.2.2基础信息，这里应该为keywords
=> chore(docs): update material-spec

packages/rax-simulator-renderer/src/renderer.ts, packages/react-simulator-renderer/src/renderer.ts, packages/renderer-core/package.json, packages/renderer-core/src/hoc/leaf.tsx, packages/renderer-core/tests/hoc/__snapshots__/leaf.test.tsx.snap, packages/renderer-core/tests/hoc/leaf.test.tsx
fix: fix the leaf hoc component fails to monitor Node changes, and modify the logic for get node
=> fix: fix the leaf hoc component fails to monitor Node changes, and modify the logic for get node

packages/shell/src/skeleton.ts
=> feat: add showArea & hideArea method for skeleton

packages/designer/src/document/document-model.ts, packages/editor-core/src/config.ts
fixed 
- https://github.com/alibaba/lowcode-engine/issues/515
- https://github.com/alibaba/lowcode-engine/issues/1077
=> fix: fixed focusNodeSelector configuration not taking effect

packages/designer/src/builtin-simulator/host.ts
Removed incorrectly calling childWhitelist hook logic during drag and drop
=> fix: removed incorrectly calling childWhitelist hook logic during drag and drop

packages/designer/src/builtin-simulator/host.ts, packages/designer/src/document/document-model.ts, packages/designer/tests/document/document-model/document-model.test.ts
Fix the problem that the childWhitelist is invalid when dragged to the root container
=> fix the problem that the childWhitelist is invalid when dragged to the root container

packages/designer/package.json, packages/designer/src/designer/offset-observer.ts, packages/plugin-outline-pane/package.json, packages/plugin-outline-pane/src/main.ts
=> use "ric-shim" replace "window.requestIdleCallback" fix #829

packages/designer/src/builtin-simulator/host.ts, packages/react-simulator-renderer/src/renderer-view.tsx
feat: 新增render notFoundComponent、faultComponent engineConfig配置
=> feat: 新增render notFoundComponent、faultComponent engineConfig配置

packages/designer/src/builtin-simulator/host.ts
fixed https://github.com/alibaba/lowcode-engine/issues/1131
=> feat: support onMouseDownHook, onChildMoveHook hooks

packages/engine/src/engine-core.ts, packages/plugin-outline-pane/src/helper/tree-title-extra.ts, packages/plugin-outline-pane/src/views/pane.tsx, packages/plugin-outline-pane/src/views/tree-title.tsx
=> 大纲树节点支持扩展渲染

packages/editor-skeleton/src/components/settings/main.ts, packages/engine/build.plugin.js, packages/engine/src/engine-core.ts, packages/ignitor/build.plugin.js, packages/rax-simulator-renderer/build.plugin.js, packages/react-simulator-renderer/build.plugin.js, packages/workspace/src/base-context.ts
fix: fix responsive invalidation caused by upgrading build-plugin-component
=> fix: fix responsive invalidation caused by upgrading build-plugin-component

packages/editor-core/src/editor.ts, packages/engine/src/engine-core.ts, packages/shell/src/api/event.ts, packages/workspace/src/base-context.ts
feat: support the use of events in workspace mode to communicate in different views
=> feat: support the use of events in workspace mode to communicate in different views

packages/editor-skeleton/src/area.ts, packages/shell/src/api/skeleton.ts
fixed https://github.com/alibaba/lowcode-engine/issues/1354
=> feat: add warning message when adding duplicate skeleton

modules/code-generator/src/generator/ProjectBuilder.ts, modules/code-generator/src/solutions/icejs.ts, modules/code-generator/src/solutions/rax-app.ts, modules/code-generator/src/types/core.ts
Feat: Hook which is used to customize original options, we can reorder/add/remove plugins/processors of the existing solution.
For example, we can add a `styleImport` plugin to **pages** slot of exsiting **icejs** solution to make below issues work without making a brand new solution.
#1291 #1052 
**styleImport.ts**
```ts
import CodeGen, {
FileType,
BuilderComponentPluginFactory,
BuilderComponentPlugin,
ICodeStruct,
IWithDependency,
ChunkType,
} from '@alilc/lowcode-code-generator';
const { COMMON_CHUNK_NAME } = CodeGen.constants;
const pluginFactory: BuilderComponentPluginFactory<unknown> = (config?: unknown) => {
const plugin: BuilderComponentPlugin = async (pre: ICodeStruct) => {
const next: ICodeStruct = {
...pre,
};
const ir = next.ir as IWithDependency;
const chunks = next.chunks; …
```
=> feat: add a hook for customizing project builder options

packages/react-simulator-renderer/src/locale/en-US.json, packages/react-simulator-renderer/src/locale/index.ts, packages/react-simulator-renderer/src/locale/zh-CN.json, packages/react-simulator-renderer/src/renderer-view.tsx
Fix missing i18n of customCreateElement, Now it can display English normally
=> fix(react-simulator-renderer): fix missing i18n of customCreateElement

packages/engine/README-zh_CN.md, packages/engine/README.md
Add contribution leaderboard badge to README and README-zh_CN
=> [Doc] Add contribution leaderboard badge to README

docs/docs/api/canvas.md, docs/docs/api/model/component-meta.md, docs/docs/api/model/resource.md, packages/designer/src/component-meta.ts, packages/designer/src/designer/designer.ts, packages/designer/src/designer/scroller.ts, packages/designer/src/simulator.ts, packages/plugin-outline-pane/src/controllers/pane-controller.ts, packages/shell/src/api/canvas.ts, packages/shell/src/model/component-meta.ts, packages/types/src/shell/api/canvas.ts, packages/types/src/shell/model/component-meta.ts, packages/types/src/shell/model/dragon.ts, packages/types/src/shell/model/engine-config.ts, packages/types/src/shell/model/index.ts, packages/types/src/shell/model/node-children.ts, packages/types/src/shell/model/preference.ts, packages/types/src/shell/model/setting-prop-entry.ts, packages/types/src/shell/model/setting-top-entry.ts, packages/types/src/shell/type/component-action.ts, packages/types/src/shell/type/field-config.ts, packages/types/src/shell/type/index.ts, packages/types/src/shell/type/scrollable.ts
1. 新增ComponentMeta文档，
3. 相关文件的lint问题修复，
4. 3. IPublicModelScrollable这个东西之前我搞错了，应该是 IPublicTypeScrollable比较合理
=> docs: add doc for api/model/component-meta

docs/docs/api/material.md, docs/docs/api/model/document-model.md, docs/docs/api/skeleton.md, docs/docs/api/workspace.md, packages/designer/src/project/project.ts, packages/shell/src/api/material.ts, packages/shell/src/api/skeleton.ts, packages/shell/src/api/workspace.ts, packages/shell/src/model/document-model.ts, packages/types/src/shell/api/material.ts, packages/types/src/shell/api/skeleton.ts, packages/types/src/shell/api/workspace.ts, packages/types/src/shell/model/document-model.ts
fixed: https://github.com/alibaba/lowcode-engine/issues/1239
=> feat: the event supplements the dispose function as the return value

packages/designer/src/designer/setting/setting-field.ts, packages/designer/src/locale/en-US.json, packages/designer/src/locale/zh-CN.json
=> fix(designer): fix i18n

packages/utils/src/build-components.ts
fixed https://github.com/alibaba/lowcode-engine/issues/1587
=> fix: fix issues with build-components

packages/renderer-core/src/renderer/addon.tsx, packages/renderer-core/src/renderer/base.tsx, packages/renderer-core/src/renderer/block.tsx, packages/renderer-core/src/renderer/component.tsx, packages/renderer-core/src/renderer/page.tsx, packages/renderer-core/src/types/index.ts, packages/renderer-core/tests/renderer/base.test.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/1571
=> refactor: rename executeLifeCycleMethod to executeLifeCycleMethod

packages/renderer-core/src/renderer/base.tsx, packages/types/src/shell/api/plugins.ts, packages/types/src/shell/type/props-map.ts, packages/types/src/shell/type/value-type.ts
fixed https://github.com/alibaba/lowcode-engine/issues/1156
=> fix: when the component is configured in a loop, the key value changes and renders error

packages/plugin-outline-pane/src/views/tree-title.tsx
修复该issue中描述的大纲树插件bug: https://github.com/alibaba/lowcode-engine/issues/1569
=> feat: disable behaviors according to components in outline-tree

packages/engine/README-zh_CN.md, packages/engine/README.md
=> fix: misspelled words

docs/docs/api/skeleton.md
Dock的使用需要在props里面定义icon属性和onClick事件
=> docs: update skeleton.md

docs/docs/api/skeleton.md
1. add Dock type
2. \t replace Space
=> docs：update skeleton.md

docs/docs/guide/expand/editor/pluginWidget.md
Dock的使用需要在props里面定义icon属性和onClick事件
=> docs: update pluginWidget.md

packages/designer/jest.config.js, packages/designer/src/designer/setting/setting-prop-entry.ts, packages/designer/src/document/node/node.ts, packages/designer/tests/designer/setting/setting-field.test.ts, packages/types/src/shell/model/node.ts
fixed https://github.com/alibaba/lowcode-engine/issues/1777
=> fix: fix the problem that the props value appears when the name is 0

modules/code-generator/example-schema.json, modules/code-generator/example-schema.json5, modules/code-generator/src/index.ts, modules/code-generator/src/plugins/common/styleImport.ts, modules/code-generator/src/solutions/icejs.ts, modules/code-generator/src/solutions/icejs3.ts, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo1/expected/demo-project/src/pages/Test/index.jsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo2/expected/demo-project/src/pages/Test/index.jsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo3/expected/demo-project/src/pages/Test/index.jsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo6-literal-condition/expected/demo-project/src/pages/Test/index.jsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo9-datasource-engine/expected/demo-project/src/pages/$/index.jsx, modules/code-generator/tests/fixtures/test-cases/react-app/demo1/expected/demo-project/src/pages/Test/index.jsx, modules/code-generator/tests/fixtures/test-cases/react-app/demo2/expected/demo-project/src/pages/Test/index.jsx, modules/code-generator/tests/fixtures/test-cases/react-app/demo3/expected/demo-project/src/pages/Test/index.jsx, modules/code-generator/tests/fixtures/test-cases/react-app/demo6-literal-condition/expected/demo-project/src/pages/Test/index.jsx, modules/code-generator/tests/fixtures/test-cases/react-app/demo9-datasource-engine/expected/demo-project/src/pages/$/index.jsx
feat: add styleImport plugin which handles style import of some fundamental materials
=> feat: add styleImport plugin

packages/designer/src/designer/setting/setting-field.ts, packages/designer/tests/designer/setting/setting-field.test.ts
fixed https://github.com/alibaba/lowcode-engine/issues/1831
=> feat(SettingField): Add support for JSExpression type value change in field

packages/renderer-core/src/renderer/component.tsx
方便排查一些组件问题，如在 didUpdate 中调用 setState 导致的设计器渲染性能大幅下降的问题。
=> feat: add componentRenderer lifeCycles log

packages/engine/README-zh_CN.md, packages/engine/README.md
=> docs: add awesome badge to README

packages/editor-skeleton/src/components/popup/index.tsx
目前配置都是固定的，对于一些简单定制化的需求无法满足，比方宽度、点击外部区域关闭等
=> feat: popup可以接受外部参数

packages/renderer-core/src/renderer/base.tsx
resolve issue: https://github.com/alibaba/lowcode-engine/issues/2010
=> fix: return first if input schema is a react dom

modules/code-generator/package.json, modules/material-parser/package.json, packages/designer/package.json, packages/editor-core/package.json, packages/editor-skeleton/package.json, packages/engine/package.json, packages/ignitor/package.json, packages/plugin-designer/package.json, packages/plugin-outline-pane/package.json, packages/rax-renderer/package.json, packages/rax-simulator-renderer/package.json, packages/react-renderer/package.json, packages/react-simulator-renderer/package.json, packages/renderer-core/package.json, packages/shell/package.json, packages/types/package.json, packages/utils/package.json, packages/workspace/package.json, scripts/set-repo.js
给现有的包设置 repository bugs homepage 从 npm 首页查询容易找到源码。
写了个脚本，后续有转移内部包开源需要修改的，可以直接执行 `node scripts/set-repo.js`
Closes: https://github.com/alibaba/lowcode-engine/issues/1070
=> chore: set repo

packages/plugin-outline-pane/src/controllers/pane-controller.ts, packages/plugin-outline-pane/src/controllers/tree-node.ts, packages/plugin-outline-pane/src/controllers/tree.ts, packages/plugin-outline-pane/src/views/tree-branches.tsx, packages/plugin-outline-pane/src/views/tree-node.tsx, packages/plugin-outline-pane/src/views/tree-title.tsx, packages/plugin-outline-pane/src/views/tree.tsx
closes https://github.com/alibaba/lowcode-engine/issues/2139
=> fix(outline-pane): tree does not change when doc.importSchema call

packages/renderer-core/src/hoc/leaf.tsx
Closes: https://github.com/alibaba/lowcode-engine/issues/2154
=> fix: fix the problem caused by props.children is [] by default in leaf

packages/renderer-core/jest.config.js, packages/renderer-core/src/utils/is-use-loop.ts, packages/renderer-core/tests/utils/is-use-loop.test.ts
fixed https://github.com/alibaba/lowcode-engine/issues/2172
=> fix(render-core): fix when designMode is false & loop is null, isUseLoop should return true

packages/plugin-designer/src/index.tsx
1. 增加支持监听 requestHandlersMap config 更新的逻辑。
=> feat: listen for the logic of requestHandlersMap config update

packages/plugin-outline-pane/src/controllers/tree.ts
监听history变更事件更新大纲树。
https://github.com/alibaba/lowcode-engine/issues/2228
=> fix: the action of history would not update outline tree

modules/code-generator/src/plugins/project/framework/icejs3/plugins/packageJSON.ts, modules/code-generator/src/plugins/project/framework/icejs3/template/files/document.ts, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo1/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo1/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo2-utils-name-alias/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo2-utils-name-alias/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo2/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo2/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo3/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo3/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo4/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo4/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo5/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo5/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo6-literal-condition/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo6-literal-condition/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo7-literal-condition2/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo7-literal-condition2/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo8-datasource-prop/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo8-datasource-prop/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo9-datasource-engine/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo9-datasource-engine/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo_10-jsslot/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo_10-jsslot/expected/demo-project/src/document.tsx, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo_11-jsslot-2/expected/demo-project/package.json, modules/code-generator/tests/fixtures/test-cases/icejs3-app/demo_11-jsslot-2/expected/demo-project/src/document.tsx
fixes this issue: https://github.com/alibaba/lowcode-engine/issues/2296
=> fix: lock some ice libs && next resource 404

modules/code-generator/src/generator/ProjectBuilder.ts, modules/code-generator/src/types/core.ts
1. generateTemplate 生成项目骨架函数支持传入上下文 parseResult
=> feat: generateTemplate fun support context

packages/plugin-outline-pane/src/index.tsx
fix: https://github.com/alibaba/lowcode-engine/issues/2323
=> fix: Optimize the initialization method for masterPaneController

packages/shell/src/model/window.ts, packages/types/src/shell/type/resource-type-config.ts, packages/workspace/src/resource.ts, packages/workspace/src/window.ts, packages/workspace/src/workspace.ts
fixed: https://github.com/alibaba/lowcode-engine/issues/2314
=> refactor: defaultViewType renamed to defaultViewName

packages/designer/src/builtin-simulator/node-selector/index.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/2369
=> feat: after the component title is modified, update the title of the ComponentAction area

packages/editor-skeleton/src/transducers/parse-func.ts
fixed https://github.com/alibaba/lowcode-engine/issues/2390
=> fix: logger is not defined error in transformStringToFunction

packages/renderer-core/src/renderer/base.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/2364
=> fix: fix utils under appHelper will not be updated when props.appHelper is updated

docs/docs/api/workspace.md, packages/editor-skeleton/src/skeleton.ts, packages/shell/src/api/workspace.ts, packages/workspace/src/workspace.ts
fixed https://github.com/alibaba/lowcode-engine/issues/2470
=> feat(workspace): add workspace.skeleton api

packages/utils/src/logger.ts
修复 issues https://github.com/alibaba/lowcode-engine/issues/2498
=> fix: make the color of the logger more highlighted

packages/react-simulator-renderer/src/locale/index.ts
fixed  https://github.com/alibaba/lowcode-engine/issues/2505
=> feat: suport more locale config

packages/designer/src/builtin-simulator/host.ts, packages/designer/src/designer/designer.ts, packages/designer/src/designer/scroller.ts, packages/utils/src/app-helper.ts, packages/utils/src/asset.ts, packages/utils/src/logger.ts
=> fix: some spell error

packages/designer/src/builtin-simulator/create-simulator.ts, packages/types/src/assets.ts
=> feat: make asset support es module

packages/designer/src/component-actions.ts
=> fix: 复制时防止 ref id 重复

packages/renderer-core/src/renderer/base.tsx
fixed https://github.com/alibaba/lowcode-engine/issues/2578
=> fix: fixed the problem caused by component list being overwritten by Hoc

packages/designer/src/document/document-model.ts, packages/shell/src/model/document-model.ts
fixed https://github.com/alibaba/lowcode-engine/issues/2577
=> fix: fix document.onMountNode parameters

packages/renderer-core/src/hoc/index.tsx
fix https://github.com/alibaba/lowcode-engine/issues/2596
参考
https://github.com/alibaba/lowcode-engine/blob/main/packages/renderer-core/src/hoc/leaf.tsx#L196-L198
=> fix: import schema 之后 cache 判断错误(#2596)

packages/types/src/shell/type/prop-types.ts
fixed https://github.com/alibaba/lowcode-engine/issues/2644
=> feat(types): add IPublicTypeInstanceOf to prop-types

packages/editor-skeleton/src/components/widget-views/index.tsx
=> chore: remove useless code

packages/designer/src/document/node/props/prop.ts, packages/designer/tests/document/node/props/prop.test.ts, packages/designer/tests/fixtures/schema/form.ts
修复此问题 [https://github.com/alibaba/lowcode-engine/issues/2618](url)
=> fix(exportschema): exportSchema(IPublicEnumTransformStage.Save) type conver

packages/designer/src/document/node/node-children.ts
=> fix: trigger node.add event on mergeChildren

packages/designer/src/designer/clipboard.ts, packages/types/src/shell/api/material.ts
fixed https://github.com/alibaba/lowcode-engine/issues/2842
fixed https://github.com/alibaba/lowcode-engine/issues/2841
=> fix(canvas): clipboard init error

docs/docs/demoUsage/makeStuff/dialog.md
fixed https://github.com/alibaba/lowcode-engine/issues/2876
=> docs(demo): add dialog use desc

packages/engine/README-zh_CN.md, packages/engine/README.md
readme中参与共建的文章链接两个已经失效，其中3已经被删除，1环境调试修正了链接
=> docs(readme): update participation url

packages/engine/README-zh_CN.md
=> docs: add star history to README

.github/CODEOWNERS, .github/workflows/publish engine.yml
=> chore: update code owners

packages/plugin-outline-pane/src/controllers/tree-node.ts, packages/plugin-outline-pane/src/controllers/tree.ts, packages/plugin-outline-pane/src/views/tree-title.tsx, packages/renderer-core/tests/renderer/__snapshots__/renderer.test.tsx.snap
=> fix: update outline tree when node loop property changes
